void STinit(int);
int STcount(void);
void STinsert(Item);
Item STsearch(Key);
void STdelete(Item);
Item STselect(int);
void STsort(void (*visit)(Item));
void search(int);
void STshowAll();
void STprintSearchAverage(Key*, int);
void STprintSearchAverageFail(Key*, int);
